import{a as w,S as v,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const S="52717192-d6fe3ca55091e661240dd4318",q="https://pixabay.com/api/";async function f(o,e){const r={key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};return(await w.get(q,{params:r})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b> ${r.likes}</p>
        <p><b>Views</b> ${r.views}</p>
        <p><b>Comments</b> ${r.comments}</p>
        <p><b>Downloads</b> ${r.downloads}</p>
      </div>
    </a>`).join("");m.insertAdjacentHTML("beforeend",e),E.refresh()}function B(){m.innerHTML=""}function p(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function b(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const M=document.querySelector(".form"),$=document.querySelector(".load-more");let l="",i=1,u=0;M.addEventListener("submit",O);$.addEventListener("click",I);async function O(o){if(o.preventDefault(),l=o.target.elements.searchQuery.value.trim(),i=1,B(),c(),!l){n.warning({title:"Oops!",message:"Please enter a search term!"});return}p();try{const e=await f(l,i);if(u=e.totalHits,e.hits.length===0){n.info({title:"No results",message:"Try a different keyword."});return}g(e.hits),u>i*15?b():(c(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(e){n.error({title:"Error",message:"Something went wrong, try again later."}),console.error(e)}finally{L()}}async function I(){i+=1,p(),c();try{const o=await f(l,i);g(o.hits);const e=document.querySelector(".gallery .gallery-item");if(e){const{height:a}=e.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}document.querySelectorAll(".gallery .gallery-item").length>=u?(c(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})):b()}catch(o){n.error({title:"Error",message:"Something went wrong, try again later."}),console.error(o)}finally{L()}}
//# sourceMappingURL=index.js.map
