import{a as b,S as w,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const v="52717192-d6fe3ca55091e661240dd4318",S="https://pixabay.com/api/";async function f(s,t){const r={key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await b.get(S,{params:r})).data}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function p(s){const t=s.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b> ${r.likes}</p>
        <p><b>Views</b> ${r.views}</p>
        <p><b>Comments</b> ${r.comments}</p>
        <p><b>Downloads</b> ${r.downloads}</p>
      </div>
    </a>`).join("");h.insertAdjacentHTML("beforeend",t),q.refresh()}function E(){h.innerHTML=""}function g(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function B(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}let i="",n=1,u=0;const M=document.querySelector(".search-form"),$=document.querySelector(".load-more");M.addEventListener("submit",O);$.addEventListener("click",P);async function O(s){if(s.preventDefault(),i=s.target.searchQuery.value.trim(),n=1,E(),d(),!i){a.warning({title:"Oops",message:"Please enter a search term!"});return}g();try{const t=await f(i,n);if(u=t.totalHits,t.hits.length===0){a.error({title:"No results",message:"Nothing found for your query."});return}p(t.hits),n*15<u?B():(d(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong, try again later."})}finally{L()}}async function P(){n++,g();try{const s=await f(i,n);p(s.hits),n*15>=u&&(d(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}));const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Something went wrong, try again later."})}finally{L()}}
//# sourceMappingURL=index.js.map
